# .github/workflows/publish-devcontainer.yml
name: Publish Universal DevContainer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/universal/.devcontainer/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      REPO: brandonc98/devcontainers-custom-images

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Dev Container Image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/universal
          imageName: ghcr.io/${{ env.REPO }}/universal
          cacheFrom: ghcr.io/${{ env.REPO }}/universal
          push: always
